### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by Highstorm** [alankarmisra/SwiftSignatureView#10]
Hi there,

thanks for keeping it up to date with swift 2.3 but
will there be a swift 3.0 branch in the near future?
Most of the other pods are changing to 3.0 which makes your lib unuseable.

cheers,

**Comment by alankarmisra** [comment]
Yes. I intend to release a version 3.0 branch by the end of this week, maybe sooner.

**Comment by alankarmisra** [comment]
The library has been updated to Swift 3.0. Cheers,
