### ISSUE TITLE
Fresh install seems to think pod is not using Swift 3.0

### ISSUE THREAD

**Issue by Pinwheeler** [alankarmisra/SwiftSignatureView#11]
Getting the following compile-time error in SwiftSignatureView

> “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

This is on a newly-imaged machine with a completely fresh install of everything.

When I open the xcworkspace, I get a prompt to convert to swift 3, when I comply with the conversion- I get a ton of breaking changes, things like ```Expressions are not allowed at the top level```

**Comment by alankarmisra** [comment]
What version of Cocoapods are you using? If you don't have >= 1.1.0.rc.2, try installing the latest beta version by running:

sudo gem install cocoapods --pre

Let me know if this doesn't work for you and we can try something else.

**Comment by Pinwheeler** [comment]
I was not using the beta version of cocoapods, it seems like that would probably work.

I got it working by just copying over your SwiftSignatureView class

**Comment by alankarmisra** [comment]
Alright. Yeah, I think the production version of Cocoapods is generating Swift 2.3 projects by default which creates issues with 3.0 Cocoapods. The beta version fixes this issue. Glad you got your fix! Consider switching to beta as a temporary measure if you intend to use other Swift 3.0 cocoapods. My two cents.
