### ISSUE TITLE
EXC_BAD_ACCESS in signatureView.delegate = self

### ISSUE THREAD

**Issue by michael-mckenna** [alankarmisra/SwiftSignatureView#12]
I have placed signatureView.delegate = self in viewDidLoad like in the example, yet I'm still getting a crash.

**Comment by alankarmisra** [comment]
Can you attach a minimal XCode project that reproduces your problem so I can try and ascertain the problem?

**Comment by michael-mckenna** [comment]
I needed to add "SwiftSignatureView" as the module in the storyboard then it worked.

**Comment by FahdSaif** [comment]
Hi Michael, I know the issue is closed, but we are faced with the similar error, and thats how i landed here, what do you mean when you say "I needed to add "SwiftSignatureView" as the module in the storyboard then it worked.", how?

**Comment by JohnLMacFarlane** [comment]
You need to go to the Storyboard, select the View where the signature is located and then go to the Identity Inspector and under Custom Class, assign it the SwiftSignatureView Class.
<img width="1165" alt="Screen Shot 2019-05-01 at 6 35 42 AM" src="https://user-images.githubusercontent.com/39962152/57019814-62701300-6bdc-11e9-9330-09f884ce2ea4.png">
