### ISSUE TITLE
Unknown class _TtC18SwiftSignatureView18SwiftSignatureView in Interface Builder file.

### ISSUE THREAD

**Issue by manjunathgudisi** [alankarmisra/SwiftSignatureView#15]
HI Alankar,

Im adding "SwiftSignatureView" from CocaPods. Project is compiling fine. But, when I runt he app on my iPhone, I get below message in console.

`Unknown class _TtC18SwiftSignatureView18SwiftSignatureView in Interface Builder file.`

Attached the screenshot. Can you help me where Im doing wrong.

- Manju
![screen shot 2017-02-11 at 10 28 43 am](https://cloud.githubusercontent.com/assets/6059076/22851345/f9b7fc2a-f044-11e6-9528-a0e6b6f5a7f1.jpg)

**Comment by alankarmisra** [comment]
Have you made sure the SwiftSignatureView.swift file has the correct Target membership? It should have "SwiftSignatureView" as Target. Cocoapods should have done this automatically for you, but make sure it has. Let me know if that doesn't fix it.

![screen shot 2017-02-11 at 11 02 17 am](https://cloud.githubusercontent.com/assets/762834/22852282/ddf0e9de-f049-11e6-9a7f-576cc55a211e.png)
