### ISSUE TITLE
signature setter should be open

### ISSUE THREAD

**Issue by RyuX51** [alankarmisra/SwiftSignatureView#25]
The signature setter should be open, because sometimes you have to set fill a present signature (back) into the view. Example in my case: A generic backend generated form in a TableView with reusable cells.

**Comment by alankarmisra** [comment]
Fixed in 2.2.0.

**Comment by for4wall** [comment]
Hi alankarmisra,

It seems this is not available from version 3.0.0 or I'm missing something.
Can you please check and answer it?
