### ISSUE TITLE
SwiftUI Version

### ISSUE THREAD

**Issue by blacktop** [alankarmisra/SwiftSignatureView#29]
Can you make a SwiftUI version or an example of how to use in a SwiftUI based app please?

Thank you for making an awesome package!

**Comment by godefroydlb** [comment]
How did you use it ?

**Comment by Faaiez** [comment]
Did you manage to use this package in SwiftUI?

**Comment by Faaiez** [comment]
Did you get to use this package in SwiftUI?

**Comment by grandviewsound** [comment]
Also wondering how to use it with SwiftUI.

**Comment by dannydenovi** [comment]
Same here
