### ISSUE TITLE
Self.bounds in SwiftSignatureView can be non-integral

### ISSUE THREAD

**Issue by mikerz** [alankarmisra/SwiftSignatureView#4]
In the case that your bounds have a fractional dimension, for example a height of 480.5 -- perfectly valid in terms of pixels under a 2x scale factor, your image will become corrupted -- it will shift upward and become fuzzier as the user pans. This was the issue I was having after using a view that was laid out in a storyboard. 

You can fix this in one of two ways:

1) On line 82 and 105 of SwiftSignatureView change 
`let rect = self.bounds`
to 
`let rect = CGRectIntegral(self.bounds)`

Or, make your image context take scale factor into consideration and change lines 83 and 106 to
`UIGraphicsBeginImageContextWithOptions(rect.size, false, UIScreen.mainScreen().scale)`

**Comment by ed-mejia** [comment]
@mikerz Thanks for the information, I was having the same issue because I'm presenting the signature view via MZFormSheetPresentationViewController, so thanks to your comment I was able to solve the issue, this should be updated in the main repository!

**Comment by alankarmisra** [comment]
Sorry for the delay in the updates guys. I'm currently traveling but should be able to update the code in the next couple of days. Thank you for the fixes! Will update soon.

**Comment by alankarmisra** [comment]
Chris Grant's pull request fixes this. 
https://github.com/alankarmisra/SwiftSignatureView/pull/6
I'll release a new Cocopod version in a bit.
