### ISSUE TITLE
How to make a signature with thin strokes?

### ISSUE THREAD

**Issue by alien142** [alankarmisra/SwiftSignatureView#49]
I solved it

**Comment by gopalkohli** [comment]
Please share your code

**Comment by alien142** [comment]
> Please share your code
Try it
signature_view.minimumStrokeWidth = 0.5
signature_view.maximumStrokeWidth = 2.0

**Comment by alien142** [comment]
Try it: 
`signature_view.minimumStrokeWidth = 0.5
        signature_view.maximumStrokeWidth = 2.0`

**Comment by alien142** [comment]
Try it:
`signature_view.minimumStrokeWidth = 0.5
 signature_view.maximumStrokeWidth = 2.0`

**Comment by alien142** [comment]
Try it:
signature_view.minimumStrokeWidth = 0.5
signature_view.maximumStrokeWidth = 2.0
