### ISSUE TITLE
Crash on iOS 15 (simulator)

### ISSUE THREAD

**Issue by Ceroce** [alankarmisra/SwiftSignatureView#55]
Hi,

I've observed a crash when running on the iOS 15 simulator version 13.0 (build 970), the version distributed with 13.0 beta 5 (13A5212g).

It is systematic and occurs in `PencilKitSignatureView.initialize()`.
On the call to `resetTool()`, I get a `EXC_BAD_ACCESS (code=1, address=0x0)`.
I don't understand why and I am investigating.

I attached a simple projet which reproduces the problem. It does work on older versions of iOS.
[EssaiSignature.zip](https://github.com/alankarmisra/SwiftSignatureView/files/7077058/EssaiSignature.zip)

**Comment by Ceroce** [comment]
I tried with the Sample projet in the SwiftSignatureView repo and it crashes as well.

**Comment by Ceroce** [comment]
It crashes when setting `canvas.tool`. It looks like a bug on Apple's side, that I can't reproduce on a minimal example yet.

I tried setting the tool with a delay, but it does not work either.

**Comment by mjulienbf** [comment]
We have the same issue here. Any hope someone will fix it soon?

**Comment by Ceroce** [comment]
It seems to work on the simulator Version 13.0 (970).

**Comment by Ceroce** [comment]
I checked on iPadOS 15.0 (19A344) and it works as well.

Since it works on the Release Candidate version, I'm closing this issue.
