### ISSUE TITLE
Issue when dark Mode 'stroke Color'

### ISSUE THREAD

**Issue by ouberghouz** [alankarmisra/SwiftSignatureView#57]
this issue happened when dark mode is on.
when the stroke color is setted to white, the exported image color is black, and when the stroke color is setted to black, the exported image color is white.

**Comment by ouberghouz** [comment]
the issue is resolved in some pull request 'T-Pro:feature/darkModeFix'

**Comment by seth35us** [comment]
This issue does not appear to be fixed. I am on version 3.2.0. The exported image color is still white.
